FROM ubuntu:14.04.3

#RUN echo 'exit 0' > /usr/sbin/policy-rc.d; chmod 0755 /usr/sbin/policy-rc.d
RUN apt-get update
RUN apt-get install -y gcc g++ python python-nose2 python-mock
RUN apt-get install -y python-pygresql python-dateutil python-yaml python-unidecode
